# [START cloudbuild_npm_node]
steps:
# Install dependencies
- name: node
  entrypoint: npm
  args: ['install']
# Run tests
- name: node
  entrypoint: npm
  args: ['test']
# Run custom commands
- name: node
  entrypoint: npm
  args: ['run', 'build']
# [END cloudbuild_npm_node]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/business-transformers/my-source-repo-suchita/nodejs-proj:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'configure-docker', 'asia-south1-docker.pkg.dev', '--quiet' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/business-transformers/my-source-repo-suchita/nodejs-proj:$SHORT_SHA']
#this is test repo
#This is main branch
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=suchita-cluster-gke'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'my-source-repo-suchita', 
   'my-source-repo-suchita=asia-south1-docker.pkg.dev/business-transformers/my-source-repo-suchita/nodejs-proj:$SHORT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=suchita-cluster-gke'
options:
  workerPool:
    name: 'projects/$WORKERPOOL_PROJECT_ID/locations/$REGION/workerPools/my-pool'
#options:
  #workerPool:
    #'projects/$GOOGLE_CLOUD_PROJECT/locations/us-central1/workerPools/suchita-pvt-worker-pool'
images: 
- 'asia-south1-docker.pkg.dev/business-transformers/my-source-repo-suchita/nodejs-proj:$SHORT_SHA'

