apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: my-source-repo-suchita
  name: my-source-repo-suchita
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-source-repo-suchita
  template:
    metadata:
      labels:
        run: my-source-repo-suchita
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/business-transformers/my-source-repo-suchita/nodejs-proj:19
        name: my-source-repo-suchita
        ports:
        - containerPort: 3000
