kind: Service
apiVersion: v1
metadata:
  name: my-source-repo-suchita
spec:
  selector:
     run: my-source-repo-suchita
  ports:
  - protocol: TCP
    port: 3000  
    targetPort: 3000
  type: LoadBalancer
